<?php

declare(strict_types=1);

namespace EasyDoc\Domain\FileGenerators\TypeScript;

use EasyDoc\Docs\SchemaBuilder;
use Illuminate\Support\Str;

class TypeScriptGenerator
{
    /**
     * Generate TypeScript interfaces from all registered schemas.
     *
     * @return string
     */
    public function generate(): string
    {
        $schemas = SchemaBuilder::all();
        $output = "// Auto-generated by EasyDoc\n";
        $output .= "// Do not edit manually - run 'php artisan easy-doc:generate' to update\n\n";

        foreach ($schemas as $name => $schema) {
            $output .= $this->generateInterface($name, $schema) . "\n\n";
        }

        return $output;
    }

    protected function generateInterface(string $name, array $schema): string
    {
        $interfaceName = Str::studly($name);
        $lines = ["export interface {$interfaceName} {"];

        $properties = $schema['properties'] ?? [];

        foreach ($properties as $propName => $propConfig) {
            // Handle simple mapping ['name' => 'string']
            if (is_string($propConfig)) {
                $propConfig = ['type' => $propConfig];
            }

            $tsType = $this->resolveType($propConfig);
            $nullable = $propConfig['nullable'] ?? false;

            // Check if required
            $required = in_array($propName, $schema['required'] ?? []);
            $optionalFlag = $required ? '' : '?';

            if ($nullable) {
                $tsType .= ' | null';
            }

            $lines[] = "    {$propName}{$optionalFlag}: {$tsType};";
        }

        $lines[] = "}";
        return implode("\n", $lines);
    }

    protected function resolveType(array $config): string
    {
        // Handle References
        if (isset($config['$ref'])) {
            // Ref string is usually "#/definitions/User"
            $parts = explode('/', $config['$ref']);
            return end($parts);
        }

        // Handle Types
        $type = $config['type'] ?? 'any';

        if ($type === 'array') {
            $items = $config['items'] ?? [];
            $itemType = $this->resolveType($items);
            return "Array<{$itemType}>";
        }

        return match ($type) {
            'integer', 'number', 'float', 'double' => 'number',
            'boolean' => 'boolean',
            'string', 'date', 'datetime' => 'string',
            'object' => 'any', // Fallback for generic objects
            default => 'any',
        };
    }
}
